### ISSUE TITLE
Does use SSL Flickr API links

### ISSUE THREAD

**Issue by rwmnau** [tgardner/wordpress-flickr-manager#1]
This code doesn't use the SSL version of the Flickr API links, and so doesn't work after the non-SSL version was disabled in June 2014. All that's required to correct this is updating four lines in lib\inc.flickr.php:

26-28: Change three links to https
208: change "http" to "https"

**Comment by gabrieledarrigo** [comment]
+1
Do You want a PR?

Gabriele

**Comment by tgardner** [comment]
I'll definitely take a PR for any fixes, thanks guys :)

**Comment by gabrieledarrigo** [comment]
Here You are!

https://github.com/tgardner/wordpress-flickr-manager/pull/2

**Comment by tgardner** [comment]
Perfect, thanks!
